# Generated by Django 5.1.6 on 2025-03-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_animal_uuid_alter_animalbreed_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='animal_colour',
            new_name='animal_color',
        ),
    ]
